In [1]:
import sys
import numpy as np

In [2]:
# Python List
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

List can have a lot of different type inside them (including other lists).

For Machine learning is about using a lot of data: Python List could be slow and heavy in terms of weights.

So if you are a data science is better to use numpy: numpy list are more powerful and efficent.

### Create and access to a numpy array

### Create an array

In [3]:

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1.shape

(10,)

### Create an array with arrange

In [4]:

np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Create an array with arrange and step
np3 = np.arange(0,10,2)
np3

array([0, 2, 4, 6, 8])

In [6]:
# Create an array of 0
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Create multidimensional zero array
np5 = np.zeros((2, 10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
# Create full array
np6 = np.full((10), 6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [9]:
# Create multidimensional full array
np7 = np.full((2,10), 6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [10]:
# Convert python list to np
np8 = np.array(list1)
np8

array([1, 2, 3, 4, 5])

In [11]:
# Accessing elements in a numpy array
np8[2] 

3

### Slicing numpy arrays

In [12]:
np1 = np.arange(1,10)
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Slice from beginning (right index is not included)
np1[1:5]

array([2, 3, 4, 5])

In [14]:
# Slice from something till the end
np1[5:]

array([6, 7, 8, 9])

In [15]:
# Return negative slices (right index is not included)
np1[-3:-1]

array([7, 8])

In [16]:
# Return slices with steps
np1[1:5:2]

array([2, 4])

In [17]:
# Steps on entire array
np1[::2]

array([1, 3, 5, 7, 9])

In [18]:
# Slice a 2-d array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# Pull out a single item
np2[1,2]

8

In [19]:
np2[0:3, 1:3]

array([[2, 3],
       [7, 8]])

### Universal functions

In [29]:
np1 = np.arange(-10,10)

In [32]:
# Square root
np.sqrt(np.abs(np1))

array([3.16227766, 3.        , 2.82842712, 2.64575131, 2.44948974,
       2.23606798, 2.        , 1.73205081, 1.41421356, 1.        ,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [31]:
# Absolute value
np.abs(np1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [34]:
# Exponential
np.exp(np1)

array([4.53999298e-05, 1.23409804e-04, 3.35462628e-04, 9.11881966e-04,
       2.47875218e-03, 6.73794700e-03, 1.83156389e-02, 4.97870684e-02,
       1.35335283e-01, 3.67879441e-01, 1.00000000e+00, 2.71828183e+00,
       7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03])

In [35]:
# Min / Max
print(np.max(np1))
print(np.min(np1))

9
-10


In [36]:
# Return the sign
np.sign(np1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  1,  1,  1,  1,  1,  1,
        1,  1,  1])

In [38]:
# Return the sin
np.sin(np1)

array([ 0.54402111, -0.41211849, -0.98935825, -0.6569866 ,  0.2794155 ,
        0.95892427,  0.7568025 , -0.14112001, -0.90929743, -0.84147098,
        0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])