In [1]:
import sys
import numpy as np

In [4]:
# Python List
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

List can have a lot of different type inside them (including other lists).

For Machine learning is about using a lot of data: Python List could be slow and heavy in terms of weights.

So if you are a data science is better to use numpy: numpy list are more powerful and efficent.

### Create and access to a numpy array

In [16]:
# Create an array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1.shape

(10,)

In [18]:
# Create an array with arrange
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Create an array with arrange and step
np3 = np.arange(0,10,2)
np3

array([0, 2, 4, 6, 8])

In [21]:
# Create an array of 0
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# Create multidimensional zero array
np5 = np.zeros((2, 10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
# Create full array
np6 = np.full((10), 6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [26]:
# Create multidimensional full array
np7 = np.full((2,10), 6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [28]:
# Convert python list to np
np8 = np.array(list1)
np8

array([1, 2, 3, 4, 5])

In [29]:
# Accessing elements in a numpy array
np8[2] 

3

### Slicing numpy arrays

In [39]:
np1 = np.arange(1,10)
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Slice from beginning (right index is not included)
np1[1:5]

array([2, 3, 4, 5])

In [38]:
# Slice from something till the end
np1[5:]

array([6, 7, 8, 9])

In [42]:
# Return negative slices (right index is not included)
np1[-3:-1]

array([7, 8])

In [43]:
# Return slices with steps
np1[1:5:2]

array([2, 4])

In [45]:
# Steps on entire array
np1[::2]

array([1, 3, 5, 7, 9])

In [48]:
# Slice a 2-d array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# Pull out a single item
np2[1,2]

8

In [52]:
np2[0:3, 1:3]

array([[2, 3],
       [7, 8]])

### Universal functions